inherit_from: configs/Replica/replica.yaml
data:
  scene_name: room2
  input_path: data/Replica-SLAM/Replica/room2/
  output_path: output/Replica/room2/

var:
  use_nlldepth: True
  tau_track: 10.0
  tau_registration: 10.0
  tau_lc: 10.0
  w_limit: 3.0